encoder: whisper
encoder_conf:
    whisper_model: large-v2
    dropout_rate: 0.0
    # n_mels: 128 # this is specified for whisper large-v3 and newer models, for other whisper models, please check the default n_mels in whisper.audio.N_MELS

decoder: whisper
decoder_conf:
    whisper_model: large-v2
    dropout_rate: 0.0

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    sym_sos: "<|startoftranscript|>"
    sym_eos: "<|endoftext|>"

# model selection
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 3

early_stopping_criterion: ["valid", "acc", "max"]

# plot related
use_matplotlib: true
num_att_plot: 0

# dataloader
num_workers: 4

# random seed
seed: 2022

# others
init: none
input_size: 1
normalize: null
frontend: null
use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false
accum_grad: 1
patience: 3
log_interval: 50
init_param: ["/root/.cache/whisper/large-v2.pt"] # you have to set the init model path anyway, if none is given, a bug raises at load_pretrained_model.py.

# -------------hyper-paramters below might should be specified depend on specific corpus-----------------#

# minibatch related
batch_type: folded
batch_size: 8
valid_batch_type: folded
valid_batch_size: 8 # large valid_batch_bins lead to large GPU memory, we can set it the half of batch_bins (training)

# optimization
max_epoch: 5
optim: adamw
optim_conf:
    lr: 1.0e-04
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-06
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 2000

# LoRA finetune related
use_adapter: true
adapter: dictlora4lanfusion
save_strategy: required_grad_only
adapter_conf:
    expert_path: "espnet_outputs_1/{}_whisper_DictLoRA_outputs/asr_DictLoRA_whisper-{}_{}-A1/valid.acc.ave_3best.pth" # you can specify the expert path in run.sh
    domain: null # should be specified in the run.sh
    Nbest: 3best # select from [1best, 3best, 5best, 7best], e.g., "5best" denotes using Top-5 experts
    rank: 16 # we assume that the rank of each expert are equal by default.
    dropout_rate: 0.05
    target_modules: ["query", "key", "value", "attn.out", "mlp.0", "mlp.2"]
    key_name_list: null # this will be filled automactically

