#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /home/rosie/DeepLearning/speech-toolkits/espnet/tools/miniconda/etc/profile.d/conda.sh && conda deactivate && conda activate espnet-24-1-5
